// AUTO-MANAGED FILE — do not edit manually.
// Block registration here is generated by scripts/create-block.ts (bun run make:block)
// and kept in sync by scripts/rename-block.ts (bun run rename:block).
import type { Block } from 'payload'
import { BlockMastheadBlock } from './block-masthead/schema.block'
import { BlockDetailBlock } from './block-detail/schema.block'
import { BlockHeroBlock } from './block-hero/schema.block'
import { BlockSpacerBlock } from './block-spacer/schema.block'
import { BlockHomeMastheadBlock } from './block-home-masthead/schema.block'
import { BlockHomeServicesBlock } from './block-home-services/schema.block'
import { BlockHomeAboutBlock } from './block-home-about/schema.block'
import { BlockHomePortfolioBlock } from './block-home-portfolio/schema.block'
import { BlockHomeContactBlock } from './block-home-contact/schema.block'

export const allBlocks: Block[] = [
  BlockMastheadBlock,
  BlockDetailBlock,
  BlockHeroBlock,
  BlockSpacerBlock,
  BlockHomeMastheadBlock,
  BlockHomeServicesBlock,
  BlockHomeAboutBlock,
  BlockHomePortfolioBlock,
  BlockHomeContactBlock,
]
