// AUTO-MANAGED FILE — do not edit manually.
// Block registration here is generated by scripts/create-block.ts (bun run make:block)
// and kept in sync by scripts/rename-block.ts (bun run rename:block).
import type { Block } from 'payload'
import { BlockHeroBlock } from './block-hero/schema.block'

export const allBlocks: Block[] = [BlockHeroBlock]
